# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wiki
author: Yi-Jhen, Lin
email: e-lin@groovenauts.jp
description: > # this means to ignore newlines until "baseurl:"
  I write code. I cook. I am a software engineer based in Tokyo, Japan.
  Here are some excerpts from my personal interest.
baseurl: "/wiki" # the subpath of your site, e.g. /blog
url: "http://e-lin.github.io" # the base hostname & protocol for your site
linkedin_username: yi-jhen-lin-00989466
github_username: e-lin

# Build settings
markdown: kramdown
